export const destinations = [
  {
    id: "jaflong",
    slug: "jaflong",
    name_bn: "জাফলং",
    name_en: "Jaflong",
    description_bn: "পাথর কোয়ারি, কংস নদী এবং পাহাড়ের অপরূপ সৌন্দর্য।",
    description_en: "Stone quarries, Khasi hills, and the stunning Piyain River.",
    base_cost: 2500,
    typical_duration_hours: 6,
    cover_image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    region: "sylhet",
  },
  {
    id: "ratargul",
    slug: "ratargul",
    name_bn: "রাতারগুল",
    name_en: "Ratargul Swamp Forest",
    description_bn: "বাংলাদেশের একমাত্র স্বাদু পানির জলাবন। সারি সারি গোলপাতা গাছ।",
    description_en: "Bangladesh's only freshwater swamp forest. Rows of golpata trees.",
    base_cost: 3000,
    typical_duration_hours: 5,
    cover_image_url: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800",
    region: "sylhet",
  },
  {
    id: "bisanakandi",
    slug: "bisanakandi",
    name_bn: "বিছনাকান্দি",
    name_en: "Bisanakandi",
    description_bn: "পাথরের উপর বয়ে চলা স্বচ্ছ নদী, মেঘালয়ের পাদদেশ।",
    description_en: "Crystal-clear river flowing over rocks, at the foot of Meghalaya.",
    base_cost: 2200,
    typical_duration_hours: 5,
    cover_image_url: "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=800",
    region: "sylhet",
  },
  {
    id: "lalakhal",
    slug: "lalakhal",
    name_bn: "লালাখাল",
    name_en: "Lalakhal",
    description_bn: "সারি নদীর নীল-সবুজ পানি, নৌভ্রমণের জন্য আদর্শ।",
    description_en: "Sari River's blue-green waters — perfect for boat rides.",
    base_cost: 2000,
    typical_duration_hours: 4,
    cover_image_url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
    region: "sylhet",
  },
  {
    id: "tea-gardens",
    slug: "tea-gardens",
    name_bn: "চা বাগান",
    name_en: "Tea Gardens",
    description_bn: "সিলেটের সবুজ চা বাগান, মালনীছড়া ও লাক্কাতুরা।",
    description_en: "Sylhet's lush tea estates — Malnicherra and Lakkatura.",
    base_cost: 1500,
    typical_duration_hours: 3,
    cover_image_url: "https://images.unsplash.com/photo-1564865878688-9a244444042a?w=800",
    region: "sylhet",
  },
  {
    id: "khadimnagar",
    slug: "khadimnagar",
    name_bn: "খাদিমনগর জাতীয় উদ্যান",
    name_en: "Khadimnagar National Park",
    description_bn: "প্রাকৃতিক বন, বিচিত্র প্রজাতির পাখি ও বন্যপ্রাণী।",
    description_en: "Natural forest with diverse bird species and wildlife.",
    base_cost: 1800,
    typical_duration_hours: 4,
    cover_image_url: "https://images.unsplash.com/photo-1511497584788-876760111969?w=800",
    region: "sylhet",
  },
]

export const addOns = [
  {
    id: "private-car",
    name_bn: "প্রাইভেট গাড়ি",
    name_en: "Private Car",
    price: 3500,
    type: "flat" as const,
  },
  {
    id: "photographer",
    name_bn: "প্রফেশনাল ফটোগ্রাফার",
    name_en: "Professional Photographer",
    price: 5000,
    type: "flat" as const,
  },
  {
    id: "english-guide",
    name_bn: "ইংরেজি ভাষার গাইড",
    name_en: "English-speaking Guide",
    price: 1500,
    type: "per_person" as const,
  },
  {
    id: "special-meals",
    name_bn: "বিশেষ খাবার (স্থানীয় আইটেম)",
    name_en: "Special Meals (Local Cuisine)",
    price: 800,
    type: "per_person" as const,
  },
  {
    id: "boat-upgrade",
    name_bn: "নৌকা আপগ্রেড (প্রাইভেট)",
    name_en: "Boat Upgrade (Private)",
    price: 1200,
    type: "flat" as const,
  },
]

export const packages = [
  {
    id: "pkg-jaflong-ratargul",
    slug: "jaflong-ratargul-2day",
    title_bn: "২ দিন: জাফলং + রাতারগুল",
    title_en: "2 Days: Jaflong + Ratargul",
    description_bn: "সিলেটের দুই আইকনিক গন্তব্য — পাথর কোয়ারি এবং জলাবন।",
    description_en: "Two iconic Sylhet destinations — stone quarries and swamp forest.",
    duration_days: 2,
    base_price: 5500,
    cover_image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    gallery_urls: [
      "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800",
      "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=800",
    ],
    itinerary: [
      {
        day: 1,
        title_bn: "জাফলং দর্শন",
        title_en: "Jaflong Exploration",
        activities: [
          { time: "07:00", bn: "সকালের নাস্তা", en: "Breakfast" },
          { time: "08:30", bn: "জাফলং যাত্রা", en: "Depart for Jaflong" },
          { time: "10:00", bn: "পাথর কোয়ারি ও কংস নদী", en: "Stone quarries & Khasi River" },
          { time: "13:00", bn: "দুপুরের খাবার", en: "Lunch" },
          { time: "15:00", bn: "কংস বাজার ঘুরে দেখা", en: "Khasi market visit" },
        ],
      },
      {
        day: 2,
        title_bn: "রাতারগুল জলাবন",
        title_en: "Ratargul Swamp Forest",
        activities: [
          { time: "06:30", bn: "ভোরে রওনা", en: "Early morning departure" },
          { time: "08:00", bn: "নৌকায় জলাবন ভ্রমণ", en: "Boat ride through swamp forest" },
          { time: "12:00", bn: "দুপুরের খাবার", en: "Lunch" },
          { time: "14:00", bn: "ফেরার পথে লালাখাল", en: "Lalakhal on return" },
        ],
      },
    ],
    active: true,
  },
  {
    id: "pkg-tea-lalakhal",
    slug: "tea-gardens-lalakhal-1day",
    title_bn: "১ দিন: চা বাগান + লালাখাল",
    title_en: "1 Day: Tea Gardens + Lalakhal",
    description_bn: "সবুজ চা বাগান ও নীল নদীর মিশেল।",
    description_en: "Green tea estates meet blue river waters.",
    duration_days: 1,
    base_price: 3200,
    cover_image_url: "https://images.unsplash.com/photo-1564865878688-9a244444042a?w=800",
    gallery_urls: [
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
    ],
    itinerary: [
      {
        day: 1,
        title_bn: "চা বাগান ও লালাখাল",
        title_en: "Tea Gardens & Lalakhal",
        activities: [
          { time: "07:00", bn: "সকালের নাস্তা", en: "Breakfast" },
          { time: "08:00", bn: "মালনীছড়া চা বাগান", en: "Malnicherra Tea Estate" },
          { time: "11:00", bn: "চা কারখানা পরিদর্শন", en: "Tea factory visit" },
          { time: "13:00", bn: "দুপুরের খাবার", en: "Lunch" },
          { time: "15:00", bn: "লালাখাল নৌভ্রমণ", en: "Lalakhal boat ride" },
        ],
      },
    ],
    active: true,
  },
  {
    id: "pkg-full-sylhet",
    slug: "full-sylhet-3day",
    title_bn: "৩ দিন: সম্পূর্ণ সিলেট",
    title_en: "3 Days: Complete Sylhet",
    description_bn: "জাফলং, রাতারগুল, বিছনাকান্দি, লালাখাল ও চা বাগান — সবকিছু একসাথে।",
    description_en: "Jaflong, Ratargul, Bisanakandi, Lalakhal & tea gardens — all in one.",
    duration_days: 3,
    base_price: 9500,
    cover_image_url: "https://images.unsplash.com/photo-1511497584788-876760111969?w=800",
    gallery_urls: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800",
      "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=800",
    ],
    itinerary: [
      {
        day: 1,
        title_bn: "জাফলং ও বিছনাকান্দি",
        title_en: "Jaflong & Bisanakandi",
        activities: [
          { time: "07:00", bn: "সকালের নাস্তা", en: "Breakfast" },
          { time: "08:30", bn: "জাফলং", en: "Jaflong" },
          { time: "13:00", bn: "দুপুরের খাবার", en: "Lunch" },
          { time: "15:00", bn: "বিছনাকান্দি", en: "Bisanakandi" },
        ],
      },
      {
        day: 2,
        title_bn: "রাতারগুল ও লালাখাল",
        title_en: "Ratargul & Lalakhal",
        activities: [
          { time: "06:30", bn: "ভোরে রওনা", en: "Early departure" },
          { time: "08:00", bn: "রাতারগুল নৌভ্রমণ", en: "Ratargul boat ride" },
          { time: "13:00", bn: "দুপুরের খাবার", en: "Lunch" },
          { time: "15:30", bn: "লালাখাল", en: "Lalakhal" },
        ],
      },
      {
        day: 3,
        title_bn: "চা বাগান ও বিদায়",
        title_en: "Tea Gardens & Farewell",
        activities: [
          { time: "08:00", bn: "মালনীছড়া চা বাগান", en: "Malnicherra Tea Estate" },
          { time: "11:00", bn: "চা কারখানা", en: "Tea factory" },
          { time: "13:00", bn: "বিদায় দুপুরের খাবার", en: "Farewell lunch" },
        ],
      },
    ],
    active: true,
  },
]

export const partners = [
  {
    id: "partner-1",
    name: "রফিকুল ইসলাম",
    bio_bn: "১৫ বছরের অভিজ্ঞ গাইড। জাফলং ও বিছনাকান্দির বিশেষজ্ঞ।",
    bio_en: "15 years of guiding experience. Specialist in Jaflong & Bisanakandi.",
    routes_covered: ["jaflong", "bisanakandi"],
    phone: "+8801712345678",
    photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    active: true,
  },
  {
    id: "partner-2",
    name: "সালমা বেগম",
    bio_bn: "রাতারগুল ও লালাখালের স্থানীয় গাইড। প্রকৃতিপ্রেমী।",
    bio_en: "Local guide for Ratargul & Lalakhal. Nature enthusiast.",
    routes_covered: ["ratargul", "lalakhal"],
    phone: "+8801712345679",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    active: true,
  },
  {
    id: "partner-3",
    name: "তানভীর হোসেন",
    bio_bn: "চা বাগান ও খাদিমনগর বিশেষজ্ঞ। ফটোগ্রাফার।",
    bio_en: "Tea garden & Khadimnagar specialist. Photographer.",
    routes_covered: ["tea-gardens", "khadimnagar"],
    phone: "+8801712345680",
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    active: true,
  },
  {
    id: "partner-4",
    name: "নাজমা আক্তার",
    bio_bn: "বহুভাষী গাইড। ইংরেজি ও বাংলায় পারদর্শী।",
    bio_en: "Multilingual guide. Fluent in English & Bangla.",
    routes_covered: ["jaflong", "ratargul", "bisanakandi"],
    phone: "+8801712345681",
    photo_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400",
    active: true,
  },
  {
    id: "partner-5",
    name: "কামরুল হাসান",
    bio_bn: "দীর্ঘদিনের ট্রেকিং অভিজ্ঞতা। সব গন্তব্য কভার করেন।",
    bio_en: "Long-time trekking experience. Covers all destinations.",
    routes_covered: ["jaflong", "ratargul", "bisanakandi", "lalakhal", "tea-gardens", "khadimnagar"],
    phone: "+8801712345682",
    photo_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400",
    active: true,
  },
]
